### ISSUE TITLE
Using .prettierrc file for define formatting rules

### ISSUE THREAD

**Issue by mrsum** [nvimdev/guard.nvim#102]
```lua
ft("typescript,javascript,typescriptreact"):fmt("prettier", {
   prettierrc: "${WORKSPACE}/.prettierrc" -- for example
})
```

**Comment by glepnir** [comment]
use extra argument ?

**Comment by mrsum** [comment]
is it possible to do right now? can't find in readme

**Comment by glepnir** [comment]
`fmt('prettier'):extra({'--config', 'path/to/config'})` or `--find-config-path` with path to config. ref https://prettier.io/docs/en/cli.html
