### ISSUE TITLE
Add support for linters with non-zero exit codes and read from stderr

### ISSUE THREAD

**Issue by gontzalm** [nvimdev/guard.nvim#109]
First of all, thanks for the awesome plugin.

I am trying to add the [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli) linter to guard.nvim. I encountered two issues:

- Currently `guard.nvim` does not support non-zero exit codes and `markdownlint` uses other [exit codes](https://github.com/igorshubovych/markdownlint-cli#exit-codes).
- `markdownlint` outputs linter errors (diagnostics) to `stderr`, and `guard.nvim` discards this stream.
- `markdownlint` does not have an error severity, so the `attributes.severity` key cannot be specified in the `lint.from_json` function.

Are you planning to support linters with this behaviour? I attempted to fix this adding a `valid_error_codes` tool option and other changes in the commit https://github.com/gontzalm/guard.nvim/commit/ea999619f3b17deb0fc281337da55eff5b70b1d4.

Now the linter is working with the options
```lua
local ft = require("guard.filetype")
local lint = require("guard.lint")

ft("markdown"):lint({
    cmd = "markdownlint",
    args = { "--json" },
    fname = true,
    valid_exit_codes = { 0, 1 },
    source = "markdownlint",
    parse = lint.from_json({
        source = "markdownlint",
        attributes = {
            lnum = "lineNumber",
            col = "lineNumber",
            message = "ruleDescription",
            code = function(d) return d["ruleNames"][1] end,
            severity = function(_) return "warning" end,
        }
    })
})

require('guard').setup()
```
![image](https://github.com/nvimdev/guard.nvim/assets/63603386/f86ada59-dc6d-4651-a28f-5e0a4c7bba29)

**Comment by xiaoshihou514** [comment]
Thanks for the attention! I am aware of this (#68). What I planned was separating some of the do_fmt and do_lint function into an api module. So ppl could write their own formatting/linting process when their tool it's behaving out of ordinary. 
I feel this approach makes guard core less cramped (not having to parse an ever-growing tool specification) and enables users to implement stuff like #76 and #86.
I am going to work on this after the autocmd pr gets merged.

**Comment by xiaoshihou514** [comment]
Oh and `from_json` and `from_regex` is meant to be a template for a majority of tools so it's natural that it won't fit for some of them.

**Comment by imbolc** [comment]
Just found that A`sqlfluff format` too sometimes returns formatted text to stdout with a non-zero error code if there's still issues left.

**Comment by xiaoshihou514** [comment]
> Just found that A`sqlfluff format` too sometimes returns formatted text to stdout with a non-zero error code if there's still issues left.

Yep, #150 should solve all of these :)
