### ISSUE TITLE
Prettier formatter inserts content from other buffer

### ISSUE THREAD

**Issue by leejuyuu** [nvimdev/guard.nvim#110]
Hello, thanks for making this plug-in! I have been trying the prettier formatter from the guard-collection to format the buffer on save. I generally open multiple buffers at the same time (let's say foo.ts, bar.ts, etc.). Sometimes when I save foo.ts, the formatter formats the buffer but also inserts the content of bar.ts into the buffer. 

This (seems to) happen randomly, and I currently have no clue how to reproduce this. Will appreciate any suggestion on how I can track down the problem.

**Comment by xiaoshihou514** [comment]
Hmm, this shouldn't have been possible because we keep track of the buffer number. But we will see.

**Comment by xiaoshihou514** [comment]
Stale, text insertion method and formatting logic went through a lot of changes, ppl should open new issues if something like this happens again. (with repro hopefully)
