### ISSUE TITLE
Failed to spawn .cmd executables on windows

### ISSUE THREAD

**Issue by scottmckendry** [nvimdev/guard.nvim#111]
`:checkheath guard` shows prettier as executable
![image](https://github.com/nvimdev/guard.nvim/assets/39483124/89a2ee4e-2042-4f93-9b0e-5a248162ab5a)

but when testing prettier on an HTML file I get the message:

`[Guard] failed to spawn process prettier`

This is my config:

```lua
return {
    "nvimdev/guard.nvim",
    dependencies = {
        "nvimdev/guard-collection",
    },
    event = "BufReadPre",
    config = function()
        local ft = require("guard.filetype")
        ft("go")
            :fmt({
                cmd = "goimports-reviser",
                args = { "-output", "stdout" },
                fname = true,
            })
            :append({
                cmd = "gofmt",
                stdin = true,
            })
            :append({
                cmd = "golines",
                stdin = true,
            })

        ft("lua"):fmt("lsp")

        ft("html"):fmt("prettier")

        require("guard").setup({
            fmt_on_save = true,
            lsp_as_default_formatter = false,
        })
    end,
}
```

running `cat index.html | prettier --stdin-filepath index.html` from the commandlne outputs the formatted file with no errors. 

Any ideas what I can check/test to try and get this working?

**Comment by scottmckendry** [comment]
I've just tested this on my Linux machine and can not replicate the erro - so it's isolated to Windows 11.
The exact same issue is also occurring with stylua. Works on Linux, and doesn't spawn on Windows.

gofmt is working fine in both os

**Comment by barrett-ruth** [comment]
None of us have a windows device I believe. Attach a lot of debugging info and also try to fix the issue yourself. Make sure/check that the process is executable (`vim.fn.executable`), that you can start a job with it (`uv.spawn`), etc.

**Comment by xiaoshihou514** [comment]
I personally don't see an obvious issue so :( And as you said it's your win machine only so if it's not a `uv.spawn` quirk then I am not sure how to approach this.

**Comment by UnderCooled** [comment]
> I've just tested this on my Linux machine and can not replicate the error - so it's isolated to Windows 11. The exact same issue is also occurring with stylua. Works on Linux, and doesn't spawn on Windows (which is why I'm using lsp format instead).
> 
> gofmt is working fine in both os

You need to add `.cmd` to those Node.js based tools on Windows, `uv.spawn` won't see these `.cmd` scripts as executable as `vim.fn.executable` on Windows.

**Comment by barrett-ruth** [comment]
@UnderCooled thanks for helping out with this. I looked at the `executable()` documentation and it seems like it automatically searches using the `.cmd` extension, so `uv.spawn()` failing instead does make sense.

I'm not accustomed to windows systems - isn't it true that some of the programs that, for example, guard-collection uses, could be `.cmd`, while others could be `.exe`?

If that's the case, I'm not sure how we could resolve this besides offering a warning to windows systems that no extension is specified.

**Comment by UnderCooled** [comment]
@barrett-ruth you can patch https://github.com/nvimdev/guard.nvim/blob/394317c25a6b0f0e064aebcfcf902e46fb0a04ba/lua/guard/spawn.lua#L38

```lua
local cmd = vim.fn.exepath(opt.cmd)
```
