### ISSUE TITLE
Unable to format with both ESLint & Prettier

### ISSUE THREAD

**Issue by sudogoku** [nvimdev/guard.nvim#113]
So far guard.nvim has been great & thank you for the ongoing maintenance. Especially ever since null-ls has been deprecated, I feel like more and more people will be coming here.

I am having some difficulty getting the proper configuration working for formatting with _both_ eslint & prettier, which I believe is a common use case.

After reading issue #70, I have concluded that relying on ESLint's LSP is the way to go in order to benefit from it's code actions, LSP-formatting, etc. Now this is where my problem starts. I am able to get prettier to format correctly when used by itself. But when adding ESLint, prettier formatting no longer works.

Here is my basic config:
```lua
-- Using Lazy.nvim
{
    "nvimdev/guard.nvim",
    dependencies = {
      "nvimdev/guard-collection",
    },
    config = require("configs.lsp.guard"),
  }
```

Here's what I expect to be formatting with both eslint & prettier.
`configs/lsp/guard.lua`:
```lua
return function()
    local ft = require("guard.filetype")

    ft("typescript,javascript,typescriptreact,javascriptreact,svelte")
        :fmt("lsp")
        :append("prettier")

    require("guard").setup({
        fmt_on_save = true,
        lsp_as_default_formatter = false,
    })
end
```
I have also tried switching up the order to no avail:
```lua
    ft("typescript,javascript,typescriptreact,javascriptreact,svelte")
        :fmt("prettier")
        :append("lsp")
```

I am aware there are some oddities specific to eslint LSP that may be coming into play, however, I have successfully used ESLint LSP formatting before by manually setting `client.server_capabilities.documentFormattingProvider = true` as suggested in [this thread](https://neovim.discourse.group/t/using-eslint-language-server-as-a-formatter-fix-all-eslint-errors/1966/7).

Putting ESLint-specific issues aside, I would expect something like this to at least work as suggested in issue #87:
```lua
ft("typescript,javascript,typescriptreact,javascriptreact,svelte")
  :fmt('prettier')
  :append({ fn = function() vim.cmd('EslintFixAll') end })
```

Unfortunately none of these approaches are working for me. Prettier formatting is working great by itself when I narrow it down to just:
```lua
ft("typescript,javascript,typescriptreact,javascriptreact,svelte")
  :fmt('prettier')
```

My apologies if I missed an existing issue or some part of the docs that covers this. If this is not already documented somewhere, I feel like this is a pretty common use case and would be beneficial to add in a "recipes" section somewhere, or perhaps in guard-collection?

For now, does anyone have any suggestions to get this combination working?

**Comment by xiaoshihou514** [comment]
Thanks for raising this! I'm a bit busy lately but I promise I will look into it as soon as possible

**Comment by pauldiloreto** [comment]
Here's another interesting bit of information, hopefully it might help debug?
```
-- Works
ft("typescript,javascript,typescriptreact,javascriptreact,svelte")
  :fmt('prettier')

-- ESLint LSP formatting works
ft("typescript,javascript,typescriptreact,javascriptreact,svelte")
  :fmt('lsp')

-- ESLint works, Prettier doesn't
ft("typescript,javascript,typescriptreact,javascriptreact,svelte")
  :fmt('lsp')
  :append('prettier')
  
-- Neither works
ft("typescript,javascript,typescriptreact,javascriptreact,svelte")
  :fmt('prettier')
  :append('lsp')
```

**Comment by xiaoshihou514** [comment]
![image](https://github.com/nvimdev/guard.nvim/assets/108414369/716b9afe-af0e-4967-a577-cc5e19d12080)
![image](https://github.com/nvimdev/guard.nvim/assets/108414369/de381d8e-1dfe-416a-a9fc-459a57806e98)
It seems that eslint-lsp do not have formatting capabilities? :thinking: 
```lua
vim.opt.rtp:append("/tmp/nvim-lspconfig")
require("lspconfig").eslint.setup({})
```

**Comment by xiaoshihou514** [comment]
Could you explain how you make eslint-lsp formatting work?
Currently I have this
```lua
vim.opt.rtp:append("/tmp/nvim-lspconfig")
vim.opt.rtp:append("/tmp/guard-collection")
vim.opt.rtp:append("/tmp/guard.nvim")

require("lspconfig").eslint.setup({
    on_attach = function(client, _)
        client.server_capabilities.documentFormattingProvider = true
    end,
})

local ft = require("guard.filetype")
ft("typescript"):fmt("lsp"):append("prettier")
require("guard").setup({
    fmt_on_save = true,
    lsp_as_default_formatter = false,
})
```

```
❯ /bin/ls format-test     
eslintrc.js  package.json  test.lua  test.ts
```
It would also be very helpful to provide a minimal repro file  like above :)

**Comment by pauldiloreto** [comment]
Thanks for responding @xiaoshihou514. In the original post, I linked a separate issue [linked here](https://neovim.discourse.group/t/using-eslint-language-server-as-a-formatter-fix-all-eslint-errors/1966/7). I see you have  the `client.server_capabilities.documentFormattingProvider` override in your example, so I'm not sure why `:lua vim.lsp.buf.format()` is working for you. I'll work on a minimal repro once I have some time.

That being said, even without LSP formatting, I would expect `ft('typescript'):fmt({ fn = function() vim.cmd('EslintFixAll') end }):append('prettier')` to work, as described in issue #87. Unfortunately using this approach, I can only get just `prettier` or the `EslintFixAll` function to work when they are by themselves. It does not work with both (in either order).

> 
> ```lua
> -- Prettier works
> ft("typescript,javascript,typescriptreact,javascriptreact,svelte")
>   :fmt('prettier')
> 
> -- ESLint LSP formatting works
> ft("typescript,javascript,typescriptreact,javascriptreact,svelte")
>   :fmt('lsp')
> 
> -- ESLint works, Prettier doesn't
> ft("typescript,javascript,typescriptreact,javascriptreact,svelte")
>   :fmt('lsp')
>   :append('prettier')
>   
> -- Neither works
> ft("typescript,javascript,typescriptreact,javascriptreact,svelte")
>   :fmt('prettier')
>   :append('lsp')
> ```

**Comment by glepnir** [comment]
may be some problems with asynchronous queue pipeline data synchronization. I have some new ideas recently. So I want to make some changes later. Adding some test cases might fix it

**Comment by xiaoshihou514** [comment]
> may be some problems with asynchronous queue pipeline data synchronization. I have some new ideas recently. So I want to make some changes later. Adding some test cases might fix it

Yes, I saw no code for checking whether a function formatter fails or succeeds and was wondering why prettier didn't work.

**Comment by caliguIa** [comment]
I'm also facing this issue. I've tried every combination of prettier, prettierd, eslint, vim.cmd('EslintFixAll'), using custom vim.system functions. They all work in isolation but the moment they are used together via append one or both of them fail to run. Is there any specific information I can provide here?

**Comment by xiaoshihou514** [comment]
@caliguIa This issue was raised a long time ago and things have changed a lot. Please open a new issue and follow the instructions there :)
