### ISSUE TITLE
ESLint formatting not applying correctly

### ISSUE THREAD

**Issue by pauldiloreto** [nvimdev/guard.nvim#114]
Hi all, thanks for maintaining this plugin!

Just wanted to flag an issue that I've been able to consistently reproduce with ESLint LSP's formatting feature.
Here is my basic config:
```lua
-- lazy.nvim
    {
        "nvimdev/guard.nvim",
        dependencies = {
            "nvimdev/guard-collection",
        },
        config = require("configs.lsp.guard"),
    },
```
`configs/lsp/guard.lua`:
```lua
return function()
    local ft = require("guard.filetype")

    ft("typescript,javascript,typescriptreact,javascriptreact,svelte")
        :fmt("lsp")

    require("guard").setup({
        fmt_on_save = true,
        lsp_as_default_formatter = false,
    })
end
```

Steps to reproduce:
1. Create a `test.ts` file with the following contents:
```js
import { zMethod } from "src/file3";
import { aMethod } from 'src/file1';
import { bMethod } from 'src/file2';
```
2. Create an `eslintrc.js` with the following rule & install required devDependencies:
```js
...
rules: {
    'import/order': [
      'warn',
      {
        groups: [
          ['builtin', 'external', 'internal'],
          ['parent', 'index', 'sibling'],
          'object',
          'type',
        ],
        'newlines-between': 'never',
        alphabetize: { order: 'asc', caseInsensitive: true },
      },
    ],
},
```
3. Open a fresh instance of Neovim and navigate to the `test.ts` file. Run `:GuardFmt`.
4. Expected result:
```js
import { aMethod } from 'src/file1';
import { bMethod } from 'src/file2';
import { zMethod } from "src/file3";
```
Actual result:
```js
import { aMethod } from 'src/file1';
import { zMethod } from "src/file3";
import { zMethod } from "src/file3";
```

NOTE: this only happens on the first time after opening a fresh instance of Neovim and running `:GuardFmt` the first time. After this bug happens once, I am not able to reproduce it. However, it happens consistently when restarting Neovim and running this the first time.

Additionally, this doesn't seem to be an ESLint LSP bug because the behavior works correctly when running `:EslintFixAll` in the same conditions. This also works correctly when running `:lua vim.lsp.buf.format()` under the same conditions.
This leads me to believe it is a bug with Guard.nvim's integration with `eslint-lsp`.

**Comment by xiaoshihou514** [comment]
Closing in favour of #113 for clarity :)

**Comment by pauldiloreto** [comment]
It's possible they're related, but I was seeing this issue with only eslint enabled, whereas #113 seems to be an issue with both prettier & eslint simultaneously.

Fair enough though, I can reopen this later if needed.
