### ISSUE TITLE
Saving file twice

### ISSUE THREAD

**Issue by jeffshaver** [nvimdev/guard.nvim#118]
When i `:w` a file, it writes, then formats, then writes the formatted file.

is there a way to stop this from happening? i would prefer that  i do `:w`, then it formats the contents of the buffer and then saves once.

my config:

```
ft('typescript,javascript,javascriptreact,typescriptreact'):fmt('prettier'):append('eslint_d'):lint('eslint_d')

guard.setup({
  fmt_on_save = true,
})
```

**Comment by xiaoshihou514** [comment]
I don' _think_ this is possible? guard is already using `BufWritePre` but the process is async so there is no guarantee when would it finish, and a `BufWritePre` autocmd cannot defer the write unless it is blocking... Is there a particular problem with that?

**Comment by jeffshaver** [comment]
this is specific to me setup I guess but I have a build process my whole team uses. it watches for file changes in a directory in order to kick off a compilation of the code.

but since this plugin writes twice, for every save, I run the build twice. which isn't ideal. 

I was using null-ls before this. and it stopped working for me when I upgraded prettier. so I was trying out other plugins. and this works well and is very easy to set up. 

just didn't know if there was a way to not have it be async I guess.

**Comment by xiaoshihou514** [comment]
I see. Unfourtunately guard does not allow you to format syncronously, there is an inactive pr that adds a option to not write after async format is done, I can implement that if that is of any help. Other than that, maybe you can switch to formatting manually (i.e. by using the `GuardFmt` command) which will only write once. Maybe a little function like so:

```lua
vim.keymap.set("n", "<leader>lf", function()
  if vim.tbl_isempty(require("guard.filetype")(vim.bo.ft)) then vim.cmd.write()
  else vim.cmd("GuardFmt")
end)
```

**Comment by jeffshaver** [comment]
@xiaoshihou514 I didn't realize that GuardFmt also saved after the fact. 

this is a good work around.

Thanks a ton!

**Comment by xiaoshihou514** [comment]
Glad to help!
