### ISSUE TITLE
Format on save stopped working

### ISSUE THREAD

**Issue by mathletedev** [nvimdev/guard.nvim#119]
After a `:PackerSync` updating to f4438af55feeca1f2443e917ba9f8149e0161236, guard.nvim stopped formatting my C/C++ files on save.

My guard.nvim config:

```lua
local ft = require "guard.filetype"
ft("typescript,javascript,json,css,yaml,astro,svelte"):fmt "prettier"
ft("rust"):fmt "rustfmt"
ft("lua"):fmt "stylua"
ft("python"):fmt "black"
ft("go"):fmt "gofmt"

require("guard").setup {
	fmt_on_save = true,
	lsp_as_default_formatter = true,
}
```

- Note that I set `lsp_as_default_formatter = true`, and C/C++ is using Mason's `clangd` server.

Format on save was working a few days ago with the config above (before PackerSync). I don't believe this is an issue with the command itself, as running `GuardFmt` **manually** works fine.

Update: Seems like none of Mason's servers are formatting, not just C/C++. Nix filetypes aren't getting formated by `rnix` either.
Perhaps this is an issue with `lsp_as_default_formatter` in conjunction with `fmt_on_save`? Since `:GuardFmt` by itself is working.

**Comment by mathletedev** [comment]
What do you mean by buffer change? My autocmd isn't firing even after a buffer change:

https://github.com/nvimdev/guard.nvim/assets/63214683/04ea6395-920b-4089-96a5-9f1aeb6cfe66


Thanks for the help!

**Comment by xiaoshihou514** [comment]
That's weird, could you check the output of `au Guard`?

**Comment by xiaoshihou514** [comment]
Auh, nvm, problem found, will fix today.

**Comment by xiaoshihou514** [comment]
@mathletedev Could you confirm fix?

**Comment by xiaoshihou514** [comment]
Should've been fixed, closing

**Comment by mathletedev** [comment]
> @mathletedev Could you confirm fix?

Confirmed working, but with a small change: https://github.com/nvimdev/guard.nvim/pull/122
