### ISSUE TITLE
Some code tools return "\r\n" on Windows.

### ISSUE THREAD

**Issue by UnderCooled** [nvimdev/guard.nvim#130]
This is codespell diagnostic message:

![image](https://github.com/nvimdev/guard.nvim/assets/161503/db7d6ac0-ee8d-4b2b-8b27-f9fe2088f03a)

These "^M" are "\r" characters, but not all code tools will use "\r\n" on Windows, maybe user should define a parse function to filter out these "^M"?

Tools without json output may have this issue on Windows, so guard can also fix it in `diag_fmt` function.

https://github.com/nvimdev/guard.nvim/blob/464578589f72a589036d682204454e6f0537c846/lua/guard/lint.lua#L95

```lua
message = message and message:gsub('\r', '') or ''
```

or with an OS check if?

**Comment by xiaoshihou514** [comment]
Seems like a CRLF issue, I wonder if `nvim_replace_termcode` would fix it

**Comment by UnderCooled** [comment]
I think Python-based tools have this problem.

Reference: https://github.com/python/cpython/issues/57328

**Comment by xiaoshihou514** [comment]
I was hoping there is a generic function that would handle these platform dependent quirks, which would also fix other potential CRLF related issues 🤔 But if there isn't one maybe we could apply the monkey patch you described 👍

**Comment by xiaoshihou514** [comment]
Ah, `vim.split` takes regexes, so `vim.split("\r?\n")` would solve this
