### ISSUE TITLE
Linter don't respect the `find` property.

### ISSUE THREAD

**Issue by UnderCooled** [nvimdev/guard.nvim#141]
If I setup a filetype to use LSP as formatter, I cannot set `find` property to linter?

Lots of linters have config files, without `find` property, how can you skip those paths which don't have a config file?

**Comment by xiaoshihou514** [comment]
The `find` property is used for something else
https://github.com/nvimdev/guard.nvim/blob/d4782860b7da344d7409edbe7ee3693d5b8ea226/README.md?plain=1#L95

**Comment by UnderCooled** [comment]
I'm trying to add "golangci-lint" to my guard configuration, it depends on "the current working directory should be project root directory", or it won't find imported modules in the project. I thought linter's `find` property acting like lspconfig "root_dir".

Likewise, I've added "editorconfig-checker" to my generic linters, I want it only runs when find ".editorconfig" file exist in the project root directory, how should I config this linter without `find` property?

**Comment by xiaoshihou514** [comment]
> I'm trying to add "golangci-lint" to my guard configuration, it depends on "the current working directory should be project root directory", or it won't find imported modules in the project. I thought linter's `find` property acting like lspconfig "root_dir".

I believe `guard-collection` has a config for that, you may want to take a look.

> Likewise, I've added "editorconfig-checker" to my generic linters, I want it only runs when find ".editorconfig" file exist in the project root directory, how should I config this linter without `find` property?

Hmm, maybe it has to be implemented for linters as well.

> Maybe my use case fit using efm-language-server with lspconfig or null-ls better? Adding find project root support may make guard.nvim too complex?

guard defaults to lsp root, then fallback to `vim.fn.cwd()` for formatting, I guess linters don't have that capability because there haven't been a use case yet.

Personally I find `null-ls` and `efm` a bit bloated, they essentially do the same thing as guard but they parse the diagnostics/formatted text a into lsp responses/text edits and neovim has to read it on top of that...

**Comment by UnderCooled** [comment]
Yeah, that's why I was trying to switch to guard.nvim...
My lspconfig configuration file get blaoted again. 😢

**Comment by xiaoshihou514** [comment]
OK, so there are two problems here.
- `cwd` is not configurable: we _could_ make it configurable but it seems unnecessary right now, `golangci-lint` should work without knowing the root directory (hopefully? Or if it's broken I would have to remove it from the builtins). If it really bugs you, set the buffer cwd to the root [like I did](https://github.com/xiaoshihou514/nvim/blob/main/lua/nano/builtin/autocmd.lua#L34-L839).

- missing multiple file support: that is trickier, it is not certain what we should do when we get diagnostics of unopened files. We could just cache it, but then it might get updated pretty soon and you may never open that particular file. Also this is quite linter specific, I _think_ most linters work on one file at a time. It can be achieved though with the right api, which... is planned ~long ago~, but I haven't got the capabilities to finish it yet.
