### ISSUE TITLE
Linter `fname` property is redundant

### ISSUE THREAD

**Issue by UnderCooled** [nvimdev/guard.nvim#142]
https://github.com/nvimdev/guard.nvim/blob/d4782860b7da344d7409edbe7ee3693d5b8ea226/lua/guard/lint.lua#L42

Some linter is project based, why add filename to args?

**Comment by xiaoshihou514** [comment]
Maybe, but `fname` stands for `file name`, so it does what it suggests. Also note guard gets diagnostics on a per buffer basis, so this parameter makes sense a lot of the times.
Is there a particular linter you have a problem with?

**Comment by UnderCooled** [comment]
Yes, you are right, I forget it should be a per buffer basis.🤦‍♂️
