### ISSUE TITLE
Range-formatting deletes lines

### ISSUE THREAD

**Issue by kwagi** [nvimdev/guard.nvim#145]
Any feature or api that select lines want to format, and activate with custom keymap.

**Comment by xiaoshihou514** [comment]
Huh, that shouldn't happen, I will look into this.

**Comment by xsh005** [comment]
Ah, commit f4438af broke range formatting
@glepnir https://github.com/nvimdev/guard.nvim/blob/4ffdefe0f181ea7e449f60fe94ccc967220181c5/lua/guard/format.lua#L51

**Comment by xsh005** [comment]
@Sologala I think you have to pass in the line range again and update accordingly, you could check the previous commits for reference, shouldn't be too hard of a pr :)

**Comment by xiaoshihou514** [comment]
#149
