### ISSUE TITLE
Getting `Failed to spawn process` error for custom `cmd`

### ISSUE THREAD

**Issue by Philogy** [nvimdev/guard.nvim#147]
I'm trying to configure the `forge fmt` command to run once (without additional input parameters) on every save for files of type `solidity`, this is how I'm trying to configure it:

```lua
local guard = require("guard")
local ft = require("guard.filetype")

ft("solidity"):fmt({
  cmd = "forge fmt",
  stdin = false,
})

guard.setup({
  fmt_on_save = true,
  lsp_as_default_formatter = true,
})
```

Note that `forge fmt` is installed on computer and does work (I can run `:!forge fmt`) from the command line just fine for example, however when I open up a file of type `solidity` I get a `[Guard] failed to spawn process forge fmt` error in my cmdline.

I'm running neovim `0.9.5` and the latest commit (`4ffdefe`).

Any help is appreciated!

**Comment by xiaoshihou514** [comment]
```
cmd = "forge",
args = { "fmt" }
```
