### ISSUE TITLE
Format on save not working - Manual formatting works

### ISSUE THREAD

**Issue by BennyThadikaran** [nvimdev/guard.nvim#148]
Running `:GuardFmt` works but saving the file does not run formatter.

Running `:LspInfo` shows python as detected filetype and lsp (pyright) has been loaded.
Also made sure guard.nvim and guard-collection has been loaded.

### Nvim version
NVIM v0.10.0-dev-2384+g848fc8ede
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634

Below is my basic config using Lazy as my plugin manager. 
```lua
return {
	"nvimdev/guard.nvim",
	event = "LspAttach",

	dependencies = {
		"nvimdev/guard-collection",
	},
	config = function()
		local ft = require("guard.filetype")

		ft("python"):fmt({
			cmd = "black",
			args = { "--quiet", "-l", "80", "-" },
			stdin = true,
		})

		require("guard").setup({
			fmt_on_save = true,
			lsp_as_default_formatter = true,
		})
	end,
}
```

**Comment by xiaoshihou514** [comment]
Cannot repro with the following:
```lua
vim.opt.rtp:append("/tmp/guard.nvim")
vim.opt.rtp:append("/tmp/guard-collection.nvim")
local ft = require("guard.filetype")

ft("python"):fmt({
	cmd = "black",
	args = { "--quiet", "-l", "80", "-" },
	stdin = true,
})

require("guard").setup({
	fmt_on_save = true,
	lsp_as_default_formatter = true,
})
```
```bash
cd /tmp
git clone https://github.com/nvimdev/guard.nvim
git clone https://github.com/nvimdev/guard-collection
vi -u test.lua repro.py
```
```py
print(      "foo") # gets formatted at :w
```
Could you show the output of `:au BufWritePre`? @BennyThadikaran

**Comment by BennyThadikaran** [comment]
Thanks for your time. Below is the requested output.
```
:au BufWritePre                                                                                                              
--- Autocommands ---                                                                                                                   
lsp_c_1_b_1_save  BufWritePre                                                                                                          
    <buffer=1>                                                                                                                         
              <Lua 201: /tmp/.mount_nvim.aKXqU8Q/usr/share/nvim/runtime/lua/vim/lsp.lua:793> [vim.lsp: textDocument/willSave]
```

I removed most of my plugins to make sure they weren't interfering with Guard.nvim. Still no good. `:GuardFmt` works though.
![Screenshot from 2024-05-25 21-24-44](https://github.com/nvimdev/guard.nvim/assets/19973418/459191ca-dfe9-43b5-90af-813a35d9f630)

**Comment by xiaoshihou514** [comment]
Ah, I believe I know the issue. Guard registers a `FileType` autocmd _after_ you call `setup()`, but since you are using `LspAttach` it likely happened after you entered the python file and hence it did not get properly triggered. Since you are not using lsp formatting (for python at least), why not just set the event to be `VimEnter` or `UIEnter`?

**Comment by BennyThadikaran** [comment]
Removed the `event` option and set `lazy = false` to disable lazy loading. All working perfectly now. Thank you!

Your setup was simple and very intuitive.
