### ISSUE TITLE
Built-in support more linters and formatters

### ISSUE THREAD

**Issue by mrjones2014** [nvimdev/guard.nvim#15]
If I want to make a PR to add a lot more linters and formatters that I use as I migrate from null-ls, would you be okay with 1 PR that adds a bunch, or would you prefer separate PRs for each one?

I'm looking to add:

## Linters

- eslint_d
- stylint
- luacheck
- shellcheck
- codespell

## Formatters

- eslint_d
- stylint
- prettier_d_slim
- markdownlint
- cbfmt
- stylua
- shfmt
- fish_indent
- gofmt
- swiftformat
- nixfmt

**Comment by glepnir** [comment]
thinking about how to write test case for these tools.

**Comment by barrett-ruth** [comment]
@glepnir am I good to go ahead and create a PR for several formatters (isort, djhtml, cbfmt, shfmt, prettierd)?

**Comment by glepnir** [comment]
go for it :)

**Comment by mrjones2014** [comment]
Guard.nvim was a bit too buggy for me so I switched to efm-langserver. It seems to work a lot better going through LSP.

**Comment by glepnir** [comment]
interesting. You're not filing any bugs just making some bad comments here.
