### ISSUE TITLE
Autopep8 doesn't run on save

### ISSUE THREAD

**Issue by Philogy** [nvimdev/guard.nvim#151]
Here's my guard plugin config file (ignoring the foundry-related stuff it's very basic):

```lua
local guard = require("guard")
local ft = require("guard.filetype")

ft("lua"):fmt("lsp")
ft("typescript,javascript,typescriptreact"):fmt("prettier")
ft("rust"):fmt("lsp")

ft("python"):fmt("autopep8")

ft("glsl"):fmt("lsp")

-- Allow falling back to default LSP formatting for solidity
local forge_fmt_enabled = true
vim.keymap.set("n", "\\f", function()
  forge_fmt_enabled = not forge_fmt_enabled
  local status = forge_fmt_enabled and "on" or "off"
  vim.notify("forge fmt: " .. status, vim.log.levels.INFO)
end)

-- Solidity format post save.
vim.api.nvim_create_autocmd("BufWritePost", {
  pattern = "*.sol",
  callback = function()
    if vim.bo.filetype ~= "solidity" then
      return
    end
    if forge_fmt_enabled then
      vim.fn.jobstart("forge fmt", {
        on_exit = function()
          vim.cmd("edit!")
        end
      })
    else
      vim.buf.lsp.format()
    end
  end
})

guard.setup({
  fmt_on_save = true,
  lsp_as_default_formatter = false,
})
```

Checkhealth reveals that guard is fine and **can find the autopep8 executable** (newest version according to `:PackerSync` at the time of this writing).

The only things I changed since it worked is updating my system's (MacOS) python version to 3.12 and having to install `autopep8` via `brew` because now python doesn't seem to do global packages any more?

Any help or hints are very appreciated! Loving the plugin <3

**Comment by xiaoshihou514** [comment]
Let's see what went wrong, could you confirm that the autocmds are present (via `:au Guard`)? It should have your disired buffer hooked on and also a filetype autocmd for python. Then, you may want to see the argument for autopep8, `= require("guard.filetype").python`, try it in the cmdline, does it format your file properly?

**Comment by Philogy** [comment]
Python seems to generally be there (`:au Guard` result):

```
:au Guard
--- Autocommands ---
Guard  BufWritePre
    <buffer=1>
              <Lua 330: ~/.local/share/nvim/site/pack/packer/start/guard.nvim/lua/guard/events.lua:11>
Guard  FileType
    glsl      <Lua 163: ~/.local/share/nvim/site/pack/packer/start/guard.nvim/lua/guard/events.lua:31> [guard]
    typescriptreact
              <Lua 164: ~/.local/share/nvim/site/pack/packer/start/guard.nvim/lua/guard/events.lua:31> [guard]
    typescript
              <Lua 165: ~/.local/share/nvim/site/pack/packer/start/guard.nvim/lua/guard/events.lua:31> [guard]
    javascript
              <Lua 166: ~/.local/share/nvim/site/pack/packer/start/guard.nvim/lua/guard/events.lua:31> [guard]
    python    <Lua 167: ~/.local/share/nvim/site/pack/packer/start/guard.nvim/lua/guard/events.lua:31> [guard]
    rust      <Lua 168: ~/.local/share/nvim/site/pack/packer/start/guard.nvim/lua/guard/events.lua:31> [guard]
    lua       <Lua 169: ~/.local/share/nvim/site/pack/packer/start/guard.nvim/lua/guard/events.lua:31> [guard]
    ```
    
    Not sure how exactly to enter the other thing into my cmdline (did `:=require("guard.filetype").python` and `:lua =require("guard.filetype").python`) and it only seems to show this and **not format**:
    
```
{
  formatter = { {
      args = { "-" },
      cmd = "autopep8",
      cwd = "/Users/philogy/Documents/Ethereum/vanity-mining",
      stdin = true
    } },
  <metatable> = <1>{
    __index = <table 1>,
    append = <function 1>,
    env = <function 2>,
    extra = <function 3>,
    fmt = <function 4>,
    key_alias = <function 5>,
    lint = <function 6>,
    register = <function 7>
  }
}
```

Appreciate you getting back to me so quickly on this!

**Comment by xiaoshihou514** [comment]
> ```
>     python    <Lua 167: ~/.local/share/nvim/site/pack/packer/start/guard.nvim/lua/guard/events.lua:31> [guard]
> ```

That looks promising, could you check if there are any BufWritePre autocmds if you have a python file open?

  
> ```
> {
>   formatter = { {
>       args = { "-" },
>       cmd = "autopep8",
>       cwd = "/Users/philogy/Documents/mydir",
>       stdin = true
>     } },
> ```

Now run autopep8 in your cmdline, paste some python code and pree C-d, does it give you the formatted output?

**Comment by xiaoshihou514** [comment]
Oh and btw does `:GuardFmt` work for a python file?

**Comment by Philogy** [comment]
Ok I fixed it! Turns out the issue was that the mason-installed autopep8 was broken and conflicting with the brew installed autopep8 somehow.

I noticed it because when I tried to run `:!autopep8 --in-place %` it'd tell me there was some error but also actually format the file, looks like it was calling both. Removing the mason one fixed it for me. Thanks again for your help!

**Comment by Philogy** [comment]
Maybe the checkhealth needs to be updated to do a better a check? Otherwise I'd generally close the issue, seems like more of a configuration / mason issue than a Guard one at the end of the day

**Comment by xiaoshihou514** [comment]
Cool! Regarding the executable check we are already using a pretty sophisticated c function (for some windows bs), I don't really think we could change it...? I am not that sure why it would fail in your case, but I am closing this for now :)
