### ISSUE TITLE
Error when mypy runs

### ISSUE THREAD

**Issue by samredway** [nvimdev/guard.nvim#152]
I have mypy set as my linter as such

        ft('python'):fmt('black'):lint 'mypy'

It works absolutely fine on one of my laptops and on my other it errors each time that mypy raises an issue. Ie instead of some red message in my IDE telling me that I have som kind of type error I get an actual errro in the lua runtime. Like

<img width="1210" alt="Screenshot 2024-07-28 at 22 17 08" src="https://github.com/user-attachments/assets/0a50dc12-e660-4289-9762-72224e7df7d7">

Again I do not believe this is an error with my setup which works find on another laptop and actually have no idea what could cause an issue like this as I have no idea how to debug lua in nvim! :(.  But here is my config if it helps at all:  https://github.com/samredway/samredway-nvim-config

If there is any other information you need please ask and will try and find it. This is literally the only way I have found as yet to run mypy in neovim so really keen to get it sorted out.

Version info
```
(.venv) crm:~$ nvim --version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
(.venv) crm:~$ mypy --version
mypy 1.11.0 (compiled: yes)
(.venv) crm:~$ python --version
Python 3.10.14
```

**Comment by xiaoshihou514** [comment]
Right, the error is from `vim.diagnostic.set`, so it's probably because output parsing failed. Since it worked on another machine, it's very likely that it's just mypy changed their output format, so an easy fix is just using the mypy version that was working previously (and `guard-collection` version, though I don't think anyone touched the mypy config recently). If you want this version working, copy the mypy config in guard-collection and put `vim.print` everywhere to check the original output and the parse results, make changes, and see if it's correct.

**Comment by samredway** [comment]
Hi, actually that was my first thought and I did try shifting the version and still can't get it working. On one of the machines. There is clearly some diffence on the machines but not sure what. Also its worth noting that most python projects are in virtual envs which each have their own dependencies (like mypy) bundled with them. Mypy is only really useful when it is part of the virtual env because it needs access to the installed dependencies to do teh static analysis on the your code. So often the mypy version will be out of the users control. I do have different version of python on my home machine to my work machine and potentiallly that could be a culprit I guess - but again the version is out of my control as trying to change the python version at work would mean changing the whole dependecy chain and would be a large job. Ideally I would like to try and debug this and try to find a fix. I wondered if maybe the first character of the mypy output contains a number or something like that - but could not find a way to check. The error appears to be in this block of code
```
vim.schedule(function()
      if not api.nvim_buf_is_valid(buf) or not results or #results == 0 then
        return
      end
      vd.set(ns, buf, results)
    end)
```
Which is in the gaurd.nivim/lua/lint.lua file.

I tried:
```
vim.schedule(function()
      if not api.nvim_buf_is_valid(buf) or not results or #results == 0 then
        return
      end
      vim.print('>>>>>>>>>>>>>>')
      vim.print(results)
      vd.set(ns, buf, results)
    end)
```
This kind of thing but where can I see output from the print? I hoped it might show in the vim instance in the command bar, but is there a log or something maybe? Or can I make it log somewhere. Sorry zero real experience with lua!

**Comment by samredway** [comment]
Hi thanks for the response. Its not practical unfortunately to try and match versions in all cases as different projects have different python versions and different dependencies (usually bundled in a virtual env). In this case though I was able to try changing the mypy version and it had no effect.

I did manage to debug a little as per your suggestion and believe I see the problem.

The error message is going in the 'col' field of the result object which I guess should be an int. ie I did:

![Screenshot 2024-07-29 at 08 54 52](https://github.com/user-attachments/assets/16f6d888-4e11-485c-85d9-e69c838f07a4)

Which you can see is on line 83 of the file lin.lua, and now the output to that that I see in my running vim is:

> Incompatible types in assignment (expression has type "str", variable has type "int") [assignment]

So clearly the error message that I want in the diagnostic is in teh col field which should be int. Still not sure how to fix it but will take antoher look later. Any thoughts or ideas would be welcome if something springs to mind or you know what I should be poking around in?

**Comment by xiaoshihou514** [comment]
There is no easy fix, you have to define the linter for your mypy version.

How about you take a look [here](https://github.com/nvimdev/guard.nvim/blob/main/ADVANCED.md), in the linter logic section it teaches you how to write the `parse` function. The idea is the parse function tells guard where the info lies in mypy's raw output.

What I suggest is that you copy the mypy config table from guard-collection, put some print in the parse function, and see what their output is. I can't tell you offhand what thr config should be since someone else pr-ed that config.

Just one small tip, you can't just print in the parse function, you do
```lua
vim.schedule(function()
    print(some_var)
end)
```

**Comment by samredway** [comment]
Ok I found the issue (or at least where it was introduced). The laptop that works is using an older commit that is `b066152`. On my other laptop I checked out that commit - which is actually HEAD~2 now and it works absolutely fine. I think it is likely that there was a breaking change in one of the 2 commits since. Likely in the large refactor which was in `6c3b3cb4`

```commit 6c3b3cb4e61446fa74ccec1a22f300efe541838a
Author: xiaoshihou <108414369+xiaoshihou514@users.noreply.github.com>
Date:   Sun Jul 21 14:54:05 2024 +0800

    ref!: major refactor (#150)

    closes #68 #86 #123 #109 #76 #141 #111
    ## changes
    - [x] remove uv.spawn wrapper in favour of vim.system
    - [x] `do_lint` now respects *all* config fields
    - [x] linter can now use lnum_end and col_end
    - [x] added step by step tutorial for advanced usage
    - [x] remove all version checking code, only supports 0.10+ from now on
    - [x] apply exepath fix for windows

    ## internal changes
    - [x] events now contains truly all autocmd related functions
    - [x] utils now contains execution checking functions
    - [x] use custom simpler table copy

commit b066152fe06122b047a6b3ce427a19d8b6e628ce
Author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Date:   Wed Jun 5 19:52:19 2024 +0000
```
So the working version is the b066 one. I can just revert back to that for now. I can try and dig into it and see where the change was. I have to admit that I dont know lua though :) I'm a Python dev. Perhaps knowing what commit it is in will jog your memory though.

**Comment by samredway** [comment]
I've somewhat nailed it down to this change```
      - coroutine.resume(co, table.concat(chunks))
     +  coroutine.resume(co, result.stdout)
```
This is in this PR https://github.com/nvimdev/guard.nvim/pull/150/files#diff-bc0f90d6e02a04c08ab4e9015ff7bf3215e567bfd6d6fae6e02372837426808c in the spawn.lua file. It used to return a table now it just returns a string.

I appreciate you made these changes for a reason but supporting mypy is really awesome would be great if we coudl get a fix in so it just does it (as it did previously). I must admit I have looked at this for a while and have learnt more lua than maybe I would have even wanted and am pretty stuck now as to what a fix might look like :(

**Comment by xiaoshihou514** [comment]
Ah, thanks for looking into this, it seems that I accidentally made a breaking change. Will fix asap.

**Comment by xiaoshihou514** [comment]
`table.concat` returns a string so it shouldn't be a breaking change. I will check if I accidentally made a breaking change later today.

**Comment by xiaoshihou514** [comment]
Fixed with latest commit, sorry!

**Comment by samredway** [comment]
Awesome! Thanks
