### ISSUE TITLE
Bug: Create new buffer when formatting with default lsp

### ISSUE THREAD

**Issue by TL-P7** [nvimdev/guard.nvim#154]
After updating to the latest verison of gurad.nvim, formatting lua file with the default lsp automatically creates a new buffer[No Name]. The buffer has the same content with the formatted lua file.

I am using the `GuradFmt` command and it turns out wrong, but it' s OK just wtih the builtin function `vim.lsp.buf.format()`.

The new buffer also comes out when formatting C files if `ft('c'):fmt('clang-format')` is not explicitly configured. So i think there may be something wrong with the `lsp_as_default_formatter` feature.

This is my configuration for guard.nvim.
```lua
  {
    'nvimdev/guard.nvim',
    config = function()
      local ft = require('guard.filetype')
      ft('c'):fmt('clang-format')
      ft('sh'):fmt({
        cmd = 'shfmt',
        args = { '-i', '4' },
      })
      ft('python'):fmt('black')
      ft('javascript,json,markdown'):fmt('prettier')
      require('guard').setup({
        fmt_on_save = false,
        lsp_as_default_formatter = true,
      })
    end,
    dependencies = {
      'nvimdev/guard-collection',
    },
  },

```

**Comment by xiaoshihou514** [comment]
Yes, in the latest refactor a temp buffer is used for redirecting the text edits, and is only wiped if formatting is successful. I do notice that it comes up from time to time, but without a min repo I can't really make out the fix. Is it possible that you could provide one?

**Comment by TL-P7** [comment]
> Yes, in the latest refactor a temp buffer is used for redirecting the text edits, and is only wiped if formatting is successful. I do notice that it comes up from time to time, but without a min repo I can't really make out the fix. Is it possible that you could provide one?

Thanks, but what should I provide? I have shown the only configuration for guard.nvim, should I upload a video clip showing the problem or ... ?

**Comment by xiaoshihou514** [comment]
I was going to say this doesn't happen with one file, but apparently not... Anyway, I will push a fix for a silly mistake.
As for the min repo, it should generally look like this
```lua
vim.opt.rtp:append("/path/to/guard")
vim.opt.rtp:append("/path/to/other/plugin")

-- setup ...
```
```bash
nvim --clean -u repro.lua
```

Provide that if the issue persists

**Comment by TL-P7** [comment]
Thanks for your explanation! 
Yes, I have created a min repo and the problem still exists. After updating to the latest version everything runs well like before.
