### ISSUE TITLE
Issue with diagnostic.lua:747

### ISSUE THREAD

**Issue by jpporta** [nvimdev/guard.nvim#155]
![image](https://github.com/user-attachments/assets/ce872a8c-6bd3-42ec-92c0-f5b89ebd92ee)
Looks like while setting the diagnostics to neovim

**Comment by jpporta** [comment]
should be related to #152. But this is for prettierd, I think, let me try debug what linter is giving the errors

**Comment by jpporta** [comment]
It was codespell that was giving errors for some reason. And this was bugging. Removed and working now.

**Comment by xiaoshihou514** [comment]
Should be fixed in latest commit.
