### ISSUE TITLE
Ability to split config into multiple files

### ISSUE THREAD

**Issue by vunhatchuong** [nvimdev/guard.nvim#159]
So a common pattern I use when `lazy.nvim` and other plugins is to split the config into multiple files and `lazy.nvim` will merge it before calling setup.

For example in `general.lua`:

```lua
{
    "nvim-treesitter/nvim-treesitter",
    opts = {
        ensure_installed = {
            "bash",
            "vimdoc",
            "diff",
            "html",
            "http",
            "gitignore",
        }}
}
```

And then in `go.lua`:

```lua
{
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
        vim.list_extend(opts.ensure_installed, {
            "go",
            "gomod",
            "gowork",
            "gosum",
            "templ",
        })
    end,
}
```

How do I achieve the same thing in `guard.nvim`? I tried to make a `_G.guard_filetypes = {}` and append it in each fine but it doesn't work.

**Comment by xiaoshihou514** [comment]
Hi.
I am working on this in #158 (which would take a while to be merged into this repo). It doesn't use lazy, you just use ftplugins. You could check it out at [my fork](https://github.com/xiaoshihou514/guard.nvim). Further suggestions and testing are very welcomed.

**Comment by vunhatchuong** [comment]
I've never used `ftplugin` before so this is my fault but now I have 3 `go.lua` files, which is also fine it's just a bit annoying when using Telescope to search for them.

Other than that the setup works great, the only thing is modifying `vim.g.guard_config` doesn't work at all.

`plugins.formatting`

```lua
return {
    "xiaoshihou514/guard.nvim",
    dependencies = {
        "nvimdev/guard-collection",
    },
    keys = {
        {
            "<leader>ff",
            "<CMD>Guard fmt<CR>",
            mode = { "n", "v" },
            desc = "Format buffer",
        },
    },
    config = function()
        vim.g.guard_config = {
            fmt_on_save = false,
            save_on_fmt = false,
        }
        local ft = require("guard.filetype")
        ft("*"):lint("codespell")
    end,
}
```
`ftplugin/go.lua`

```lua
local ft = require("guard.filetype")
ft("go"):fmt("lsp"):append("golines")
```

---

And also everytime I save it will format (which is expected since my config doesn't work).

But it will print out an error:
- In a `.lua` it's `[Guard]: buffer changed during formatting`.
- For `.go` it's `[Guard]: buffer changed` and the formatting behaves weirdly: I indented a line so that I can try out the formatter but then after formatting the indented line disappears completely.

**These warning doesn't appear if I use `Guard fmt`.**

**Comment by xiaoshihou514** [comment]
Thanks for the feedback! I will add some more testing regarding these options. It's a bit of a wip, so stay tuned!

**Comment by xiaoshihou514** [comment]
@vunhatchuong I think I've fixed it, would you mind trying the latest commit on my branch?

**Comment by vunhatchuong** [comment]
Yep looks like everything works flawlessly, appreciate your hard work!

**Comment by vunhatchuong** [comment]
@xiaoshihou514 Oh btw I didn't test thoroughly yesterday, I think there are some weird behaviors when `save_on_fmt = false`.

**Comment by vunhatchuong** [comment]
I think when setting `save_on_fmt = false`, `lsp` formatter in my `ft("lua"):fmt("lsp"):append("stylua")` doesn't work.

**Comment by xiaoshihou514** [comment]
I will look into that this afternoon :)

**Comment by xiaoshihou514** [comment]
@vunhatchuong I think it should be ready now!

**Comment by vunhatchuong** [comment]
Yep looks like it's fixed, I have a question:

Why does it show I have 2 formatters attached when I only have `stylua`, and also when I attach `lsp` it doesn't show up as a formatter

This is my config:
```lua
config = function()
    vim.g.guard_config = {
        fmt_on_save = false,
        save_on_fmt = false,
    }
    local ft = require("guard.filetype")
    ft("lua"):fmt("stylua")
end,
```

`Guard info`:
```bash
Settings:
fmt_on_save: false
lsp_as_default_formatter: false
save_on_fmt: false
Current buffer has filetype lua:
formatters:
{{
    fn = <function 1>
    },{ 
  args = { "-" },
  cmd = "stylua",
  cwd = "D:/.dotfiles/nvim",
  stdin = true
}}
nil
2 formatter autocmds attached
1 linter autocmds attached 
```

**Comment by xiaoshihou514** [comment]
> Why does it show I have 2 formatters attached when I only have `stylua`

Lsp format also counts as a formatter, don't you think?

> and also when I attach `lsp` it doesn't show up as a formatter

It did, it's the `fn` one.

**Comment by vunhatchuong** [comment]
Oh, the reason I was confused is because I think when I open a new buffer the LSP formatter auto attaches:

nvim `:message` output:

```bash
# :Guard fmt
[Guard]: missing config for filetype lua
# :Guard info
Error executing Lua callback:  
.../nvim-data/lazy/guard.nvim/plugin/guard.lua:43: attempt to index local 'ft' (a nil value)
stack traceback:  
.../nvim-data/lazy/guard.nvim/plugin/guard.lua:43: in function 'f'
.../nvim-data/lazy/guard.nvim/plugin/guard.lua:65: in function <.../nvim-data/lazy/guard.nvim/plugin/guard.lua:63>

# Switch to another file using telescope
# :Guard fmt
    # (return nothing)
# :Guard info
Settings:  
fmt_on_save: false  
lsp_as_default_formatter: false  
save_on_fmt: false  

Current buffer has filetype lua:  
formatters:  
{ 
  { 
    fn = <function 1> 
  } 
}
nil
2 formatter autocmds attached  
1 linter autocmd attached
```

So there are 2 things:
- I don't think `:Guard info` should return an error when no `ft` is available.
- Opening a new buffer makes LSP formatter auto-attach.

**Comment by xiaoshihou514** [comment]
> - I don't think `:Guard info` should return an error when no `ft` is available.

Oops, You are absolutely correct!

> - Opening a new buffer makes LSP formatter auto-attach.

I assume you mean setting `lsp_as_default_formatter` to false doesn't work?

**Comment by vunhatchuong** [comment]
Yeah setting `lsp_as_default_formatter` doesn't work.

**Comment by xiaoshihou514** [comment]
It seems that I totally forgot to add the code for it to work... Anyway, should be fixed now. Thanks for all that generous feedback :)

**Comment by vunhatchuong** [comment]
Yea it's fixed, did you address the 2 autocmd thing? I don't know what autocmd it is tracking but if I have nothing for the `ft` the default is 1 autocmd. Doesn't matter if I attach 1 or 2 `fmt` it will show as 2.

**Comment by xiaoshihou514** [comment]
You _should_ see zero autocmds if you don't have a config for that ft and exactly 1 if you do.

**Comment by vunhatchuong** [comment]
Yes, when I have no `fmt` and `lint`, the default is `1 formatter` and `1 linter`.

**Comment by xiaoshihou514** [comment]
*Sigh*
What does `:au Guard` say?

**Comment by vunhatchuong** [comment]
--- Autocommands ---                                                                                                                                            Guard  LspAttach                                                                                                                                                    *         <Lua 1255: .../nvim-data/lazy/guard.nvim/lua/guard/events.lua:63>

**Comment by xiaoshihou514** [comment]
I'm sure that's not all of the output?

**Comment by vunhatchuong** [comment]
Yeah that's the full output.

**Comment by xiaoshihou514** [comment]
Fixed!
