### ISSUE TITLE
clang-format formatting based on global vim settings

### ISSUE THREAD

**Issue by xavier7179** [nvimdev/guard.nvim#168]
### Feature description

I was wondering if there is a way to configure `clang-format` so that it looks for the file first, and, if not present, it does not only apply a preferred style but also sets indentation and tabs vs. space for Vim configurations? If so, could you make an example in the documentation?

**Comment by xiaoshihou514** [comment]
"File not present", meaning this is a temp buffer that's not saved yet?

**Comment by xavier7179** [comment]
I apologize. I needed clarification in the first place. I was referring to the `-style=file` option, which makes the command search for a `.clang-format` file (making it possible to have project-specific formatting rules)

**Comment by xiaoshihou514** [comment]
I think that's the default behavior given that the cwd is correct (`:pwd`)

**Comment by xavier7179** [comment]
Yes, indeed it is. Nevertheless, the `style` accepts a list of options that follow the file content structure. Unfortunately, there is no example of how to set them (and re-use the values of indents and tabs vs spaces that you can set with vim).
Moreover, the command accepts a `--fallback-style=<string>` option that should fall back to a specific style when the file is missing. Although useful, `<string>` can only be a default style and not a more complex configuration as in the `-style` version. Thus, I was wondering if your plugin can handle it using an algorithmic approach...

**Comment by xiaoshihou514** [comment]
I guess I can create an example... That might take a while.
Note that `ft("foo"):fmt` can take a function, check out the tests.
https://github.com/nvimdev/guard.nvim/blob/cc8df48248eb795b71be21f7a30f08fc47a2c22d/spec/format_spec.lua#L71
If you managed to achieve what you wanted I am just going to put your solution as an example :)

**Comment by xiaoshihou514** [comment]
https://github.com/user-attachments/assets/d98219be-19c9-47b8-8ce9-c12cbc640143

@xavier7179 

```lua
local ft = require("guard.filetype")

ft("c"):fmt(function()
	---@diagnostic disable-next-line: undefined-field
	if vim.uv.fs_stat(".clang-format") then
		return {
			cmd = "clang-format",
			stdin = true,
		}
	else
		return {
			cmd = "clang-format",
			args = {
				("--style={BasedOnStyle: llvm, IndentWidth: %d, TabWidth: %d, UseTab: %s}"):format(
					vim.bo.shiftwidth,
					vim.bo.tabstop,
					vim.bo.expandtab and "Never" or "Always"
				),
			},
			stdin = true,
		}
	end
end)
```

**Comment by xavier7179** [comment]
Thanks for the help! You are the first to support something like this. I really appreciate it (as I'm doing for your plugin, which is very unique if you program in C/C++)
