### ISSUE TITLE
Provide a formatexpr.

### ISSUE THREAD

**Issue by 231tr0n** [nvimdev/guard.nvim#177]
### Feature description

Hi! Thank you soo much for developing this wonderful plugin. Is it possible to ship a ``:h 'formatexpr'`` function with this plugin which can be used for formatting with gq motions.

**Comment by xiaoshihou514** [comment]
I personally bind `gq` to `Guard fmt` since I don't use formatexpr.

I am guessing that you need old formatexpr compatibility?

**Comment by 231tr0n** [comment]
> I personally bind `gq` to `Guard fmt` since I don't use formatexpr. It's a bit of an old concept imo and I don't really see how this improves generality of guard.
> 
> I am guessing that you need old formatexpr compatibility?

Basically I want to migrate from conform.nvim and nvim-lint to guard.nvim since this plugin provides both. But the thing is conform.nvim provides a formatexpr which I can set and use gq for formatting. That was my intention behind requesting this feature.

**Comment by xiaoshihou514** [comment]
I think in this case binding `gq` to `Guard fmt` will do.
