### ISSUE TITLE
Weird behavior of Guard Auto-Format feature.

### ISSUE THREAD

**Issue by zebra-f** [nvimdev/guard.nvim#182]
### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Fedora 41

### Output of :checkhealth guard

```console
Executable check ~
- OK npx found
- WARNING It seems that mason.nvim is installed,in which case checkhealth may be inaccurate. Please add your mason bin path to PATH to avoid potential issues.
- WARNING It seems that mason.nvim is installed,in which case checkhealth may be inaccurate. Please add your mason bin path to PATH to avoid potential issues.
- WARNING It seems that mason.nvim is installed,in which case checkhealth may be inaccurate. Please add your mason bin path to PATH to avoid potential issues.
- OK black found
- WARNING It seems that mason.nvim is installed,in which case checkhealth may be inaccurate. Please add your mason bin path to PATH to avoid potential issues.
- WARNING It seems that mason.nvim is installed,in which case checkhealth may be inaccurate. Please add your mason bin path to PATH to avoid potential issues.
```

### Output of :Guard info

```markdown
# Guard info (press Esc or q to close)
## Settings:
- `fmt_on_save`: true
- `lsp_as_default_formatter`: true
- `save_on_fmt`: true

## Current buffer has filetype python:
- 0 formatter autocmds attached
- 0 linter autocmds attached
- formatters:


{
  args = { "--quiet", "-" },
  cmd = "black",
  stdin = true
}


- linters:

```

### How to reproduce the issue

Restart nvim with my config (inside some container, and/or host machine):  
https://github.com/zebra-f/nvim-config
only difference, these lines:
```lua
vim.api.nvim_set_option("clipboard", "unnamedplus")
vim.api.nvim_set_option("scrolloff", 8)
vim.api.nvim_set_option('smartcase', true)
```
replaced with these:
```lua
vim.api.nvim_set_option_value("clipboard", "unnamedplus", {})
vim.api.nvim_set_option_value("scrolloff", 8, {})
vim.api.nvim_set_option_value('smartcase', true, {})
```

### Expected behaviour

`:w` should auto-format Python `.py` files.

### Actual behaviour

Auto-format on save works only after fresh Lazy install. Behavior shown in a recording below
[2024-12-11 22-42-35.webm](https://github.com/user-attachments/assets/8a4c4957-7a1e-45d8-9994-e42e9e6db62f)

Guard auto-formats Python (and Lua) on save only on first Neovim start. Prettier works every time for `*.js` and `*.html` files.  
`:Guard fmt` works every time as shown in the recording, `:black! %` also works. 

### The minimal config used to reproduce this issue.

```Lua
Tried with Nvim `v0.10.2`, `0.11.x-dev`, `./nvim.appimage` (`v0.10.2`) inside `Ubuntu 24.04` distrobox' container and `Fedora 41` distrobox' container, same behavior everywhere including running `./nvim.appimage` on the host (`Fedora 41 Kinoite`). 
Flatpak (v0.10.2) on the host works without any issue.
```

**Comment by xiaoshihou514** [comment]
Min repo please
```shell
        git clone https://github.com/nvimdev/guard.nvim /tmp
        git clone https://github.com/nvimdev/guard-collection /tmp
        echo "vim.opt.rtp:append('/tmp/guard.nvim')" >> /tmp/repro.lua
        echo "vim.opt.rtp:append('/tmp/guard-collection')" >> /tmp/repro.lua
```

**Comment by zebra-f** [comment]
> Min repo please
> 
> ```shell
> git clone https://github.com/nvimdev/guard.nvim /tmp
> git clone https://github.com/nvimdev/guard-collection /tmp
> echo "vim.opt.rtp:append('/tmp/guard.nvim')" >> /tmp/repro.lua
> echo "vim.opt.rtp:append('/tmp/guard-collection')" >> /tmp/repro.lua
> nvim --clean -u /tmp/repro.lua
> ```

Sorry for the late response, I was about to try and make a min config, but it looks like my issue is magically fixed (probably some updated plugin as I've deleted `~/.local/share/nvim/`. and reinstalled all the plugins again today, just for the record updating or reinstalling didn't work when I first posted here).

**Comment by xiaoshihou514** [comment]
Ah ok I'm glad the issue just disappears.

The errors don't look like they are from guard, so I will close this issue.
