### ISSUE TITLE
Trigger the format command and nothing happens

### ISSUE THREAD

**Issue by command-z-z** [nvimdev/guard.nvim#183]
### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

ubuntu22.04

### Output of :checkhealth guard

```console
guard: require("guard.health").check()

Executable check ~
- OK codespell found
- WARNING It seems that mason.nvim is installed,in which case checkhealth may be inaccurate. Please add your mason bin path to PATH to avoid potential issues.
- WARNING It seems that mason.nvim is installed,in which case checkhealth may be inaccurate. Please add your mason bin path to PATH to avoid potential issues.
- OK black found
- OK isort found
- OK docformatter found
- OK flake8 found
- WARNING It seems that mason.nvim is installed,in which case checkhealth may be inaccurate. Please add your mason bin path to PATH to avoid potential issues.
```

### Output of :Guard info

```markdown
# Guard info (press Esc or q to close)
## Settings:
- `fmt_on_save`: false
- `lsp_as_default_formatter`: false
- `save_on_fmt`: false

## Current buffer has filetype python:
- 1 formatter autocmds attached
- 2 linter autocmds attached
- formatters:


{
  args = { "--quiet", "-" },
  cmd = "black",
  stdin = true
}
{
  args = { "-" },
  cmd = "isort",
  stdin = true
}
{
  args = { "-" },
  cmd = "docformatter",
  stdin = true
}


- linters:

{
  args = { "--format", "default", "-", "--stdin-display-name" },
  cmd = "flake8",
  fname = true,
  parse = <function 1>,
  stdin = true
}
```

### How to reproduce the issue

Trigger the format command and nothing happens

### Expected behaviour

format my file.

### Actual behaviour

nothing happened.

### The minimal config used to reproduce this issue.

```Lua
{
        "nvimdev/guard.nvim",
        -- Builtin configuration, optional
        dependencies = {
            "nvimdev/guard-collection",
        },
    },
---------------------------------------------------
local ft = require('guard.filetype')

-- Assuming you have guard-collection
ft('python'):fmt('black')
    :append('isort')
    :append('docformatter')
    :lint('flake8')

ft('lua'):fmt('lsp')

ft('*'):lint('codespell')

-- Call setup() LAST!
vim.g.guard_config = {
    -- Choose to format on every write to a buffer
    fmt_on_save = false,
    -- Use lsp if no formatter was defined for this filetype
    lsp_as_default_formatter = false,
    -- By default, Guard writes the buffer on every format
    -- You can disable this by setting:
    save_on_fmt = false,
}

vim.api.nvim_set_keymap("n", "<leader>fm", "<cmd>Guard fmt<CR>", { silent = true, noremap = true })
```

**Comment by xiaoshihou514** [comment]
Seems to work on my machine?

https://github.com/user-attachments/assets/38380eec-b3b0-4d32-9b70-0c6392a40c93

Can you show me the output of

```sh
which black
which isort
which docformatter
which flake8
```
?

**Comment by command-z-z** [comment]
The output path is in the Mason path.
```
which black
which isort
which docformatter
which flake8
/home/eugene/.local/share/nvim/mason/bin/black
/home/eugene/.local/share/nvim/mason/bin/isort
/home/eugene/.local/share/nvim/mason/bin/docformatter
/home/eugene/.local/share/nvim/mason/bin/flake8
```

**Comment by glepnir** [comment]
Did you edit the file ? the format work after changedtick increase.

**Comment by command-z-z** [comment]
This is demonstration in my machine, I meet some errors but It seems to have nothing to do with guard plugin.
And I edit the file using some blank lines, trigger `Guard fmt` command.

https://github.com/user-attachments/assets/f7898765-fa7b-4ad1-9392-50c82060a976

**Comment by xiaoshihou514** [comment]
And does `:!black "%"` work? 🤔

**Comment by xiaoshihou514** [comment]
ok there's one last easy problem I can think of, try:
```lua
require('guard.util').get_cmd({ cmd = 'black' })
```
and see if they point to your mason tools.

If that looks ok we have to put print statements inside guard.

**Comment by command-z-z** [comment]
I tried the command, the video following:

https://github.com/user-attachments/assets/fcf10ab4-e1ed-499e-ad1f-4253c88959c2

I will also assist in debugging issues to further improve the stability and performance of the plugin.

**Comment by xiaoshihou514** [comment]
Erm use `vim.print` plz

**Comment by command-z-z** [comment]
ok，I re-output the result, it seems that the path of black is correct:

![Screenshot from 2024-12-14 21-21-37](https://github.com/user-attachments/assets/a1b05046-16b6-41bf-ba1e-722bc789e7c5)

**Comment by xiaoshihou514** [comment]
ok, let's do this:

Add the following under https://github.com/nvimdev/guard.nvim/blob/main/lua%2Fguard%2Fspawn.lua#L11-L11

```lua
vim.schedule(function()
    vim.print(result)
end)
```

**Comment by command-z-z** [comment]
I do this, then what should I do?
![Screenshot from 2024-12-14 22-52-07](https://github.com/user-attachments/assets/1f63413e-a890-4c6a-ad81-4f18b11fd710)

**Comment by command-z-z** [comment]
This is so weird, the same configuration works fine on my arch computer.

**Comment by command-z-z** [comment]
I deleted the configuration using `rm -rf ~/.local/share/nvim` and reinstalled guard. I found that guard can work normally. Maybe I didn't handle some things correctly before. Anyway, thank you for your careful guidance.

**Comment by xiaoshihou514** [comment]
Glad it worked for you!
