### ISSUE TITLE
While formatting (async), prevent to go to insert mode

### ISSUE THREAD

**Issue by otavioschwanck** [nvimdev/guard.nvim#20]
Sometimes i forget that i can't and the buffer just changes.  After that i lose the cursor position on insert.

**Comment by glepnir** [comment]
> Sometimes i forget that i can't and the buffer just changes.

sry what does this mean .

**Comment by otavioschwanck** [comment]
> > Sometimes i forget that i can't and the buffer just changes.
> 
> sry what does this mean .

the buffer is "upgraded" when the formatting is done.  Rubocop by example, take 1~2s to format the buffer.

If i save (auto format async start), try to type something in insert mode.  When the auto format ends, it upgrade the buffer and i lose what i typed.
![async format](https://github.com/nvimdev/guard.nvim/assets/9551316/46bd536a-859a-49c1-94a4-2868018cd729)

**Comment by glepnir** [comment]
why there no diagnostic error when you type `attribute` ? if there has diagnostic error you can set `ignore_error` to true to avoid format when have diagnostic error

**Comment by otavioschwanck** [comment]
> why there no diagnostic error when you type `attribute` ? if there has diagnostic error you can set `ignore_error` to true to avoid format when have diagnostic error

no errors on attribute

**Comment by glepnir** [comment]
hmm no any diagnostics ?
