### ISSUE TITLE
Last commit made rubocop formatter stop working

### ISSUE THREAD

**Issue by otavioschwanck** [nvimdev/guard.nvim#21]
https://github.com/nvimdev/guard.nvim/commit/5a20e74cc828aa019cf323c18a68b95bbc39802f

Now, when i save, just don't happen nothing.  The problem with the other issue: https://github.com/nvimdev/guard.nvim/issues/20
is that while is formatting, i can edit the document, and when the formatting is done, is just revert.  Is more annoying than a real bug.

The idea is just prevent to edit the formatter is running.  But now, with this commit, is just don't format anymore :(.

Calling the GuardFormat manually format correctly the buffer but don't remove the diagnostics.

**Comment by glepnir** [comment]
update and now you can use `ft('javascript, tyscript'):fmt('prettier')`

**Comment by otavioschwanck** [comment]
> update and now you can use `ft('javascript, tyscript'):fmt('prettier')`

i didn't understand your anwser, this PR is about something totally different

**Comment by glepnir** [comment]
I know but this issue fix just now. and answer #18 in there.
