### ISSUE TITLE
Diagnostics are not being cleared after formatting (rubocop)

### ISSUE THREAD

**Issue by otavioschwanck** [nvimdev/guard.nvim#22]
![image](https://github.com/nvimdev/guard.nvim/assets/9551316/8677c0d3-829b-4e43-a18f-21d2e1aa0656)

The format on save is working now, but the diagnostics are not being cleared.

**Comment by glepnir** [comment]
does `au TextChanged` and `InsertLeave`  have guard au ?

**Comment by glepnir** [comment]
okay the autocmd event create successful .so I wonder why not trigger there

https://github.com/nvimdev/guard.nvim/blob/1154a72a7094d09cae01e97de005459b6fe03d57/lua/guard/lint.lua#L16

**Comment by otavioschwanck** [comment]
Fixed in last commit!
