### ISSUE TITLE
bug: buffer is not reloaded after formatting

### ISSUE THREAD

**Issue by mrjones2014** [nvimdev/guard.nvim#23]
It formats the underlying file but I have to run `:e` to see the changes.

**Comment by mrjones2014** [comment]
Happens with markdown, using `markdownlint`, configured like:

```lua
require('guard').setup({
  ft = {
    markdown = {
      fmt = {
        cmd = 'markdownlint',
        args = { '--fix' },
        fname = true,
      },
    },
  },
})
```

**Comment by glepnir** [comment]
oh because it not support stdin so there must be reload .

**Comment by mrjones2014** [comment]
Same issue with `go` with `gofmt` and Nix with `nixfmt`.

**Comment by glepnir** [comment]
how you config `gofmt` I can't reproduce 

```lua
ft('go'):fmt({
  cmd = 'gofmt',
  args = {},
  fname = true,
})
```

![Untitled](https://github.com/nvimdev/guard.nvim/assets/41671631/5eecfc37-9efe-4f8f-ab9c-79895f2a0600)

**Comment by glepnir** [comment]
for not support `stdout` tools please config `stdout =false` then guard will reload
