### ISSUE TITLE
Formatting should not update the jump list

### ISSUE THREAD

**Issue by mrjones2014** [nvimdev/guard.nvim#26]
- Format file by saving with `:w`
- Try pressing `u` to undo last edit
- Cursor jumps to bottom of file

**Comment by glepnir** [comment]
I remember there has same issue in neovim. this is the undo behavior in neovim .

**Comment by mrjones2014** [comment]
It doesn’t happen when formatting with LSP.

**Comment by glepnir** [comment]
update i think it should be solved.

**Comment by mrjones2014** [comment]
Yeah it can definitely be solved. It doesn't happen with a lot of other formatting plugins either.

**Comment by glepnir** [comment]
close then

**Comment by mrjones2014** [comment]
Oh, I misunderstood your comment. Yeah, it is fixed by [59c1082](https://github.com/nvimdev/guard.nvim/commit/59c1082638818fe4f225b6325d69a28f3617e8d5)
