### ISSUE TITLE
lint is called multiple times when try to move line (or any other hard editing operation)

### ISSUE THREAD

**Issue by otavioschwanck** [nvimdev/guard.nvim#30]
i have this command to move lines around:

```lua
  set('x', 'J', ":m '>+1<CR>gv=gv")
  set('x', 'K', ":m '<-2<CR>gv=gv")
```

when i try to use, the computer gets super laggy and if i try to see the processes:

![image](https://github.com/nvimdev/guard.nvim/assets/9551316/889898b2-6472-4b91-8736-840591202a45)

i think guard should not run again if a lint process is already running (or at least cancel the other to run a new one)

**Comment by glepnir** [comment]
looks like it trigger multiple times Textchanged.
