### ISSUE TITLE
More versatile GuardDisable

### ISSUE THREAD

**Issue by xiaoshihou514** [nvimdev/guard.nvim#32]
Support for `GuardDisable lua` and `GuardDisable %`.
The stupid solution is just have an extra table for a "blacklist" of burnrs and fts and have do_fmt read it. Are there any tricks that can simplify the logic?

**Comment by glepnir** [comment]
receive ft from cmdline and pass into a local table (black list) .when format running check ft in it or not . also need GuardEnable ft ? usually they are pairsed

**Comment by xiaoshihou514** [comment]
Right. I will try to draft a pr soon.
