### ISSUE TITLE
Unsaved changes made during the formatting process is discarded

### ISSUE THREAD

**Issue by otavioschwanck** [nvimdev/guard.nvim#33]
On a TS file, i could delete everything in the file, when the format run, it reload the previous version (and i need to restart neovim to fix, just closing and opening the file doesn't fix it)

**Comment by glepnir** [comment]
how can i reproduce this issue ?

**Comment by otavioschwanck** [comment]
> how can i reproduce this issue ?

its very random, try to create new buffer, save, reload, paste something, do undo, its very hard to happen (happened 2 times in one week of work)

**Comment by glepnir** [comment]
let me try it with many times. hope i can reproduce this.

**Comment by barrett-ruth** [comment]
tried this many times and unable to repro.... think we should close issues with limited repro otherwise they'll be up forever.

**Comment by xiaoshihou514** [comment]
[Screencast from 2023-08-23 16-40-28.webm](https://github.com/nvimdev/guard.nvim/assets/108414369/7ade22f7-8c08-49f8-8927-a32b0380271e)

Could repro, but I imagine this would hardly happen in real work, right?
If more people complain about this maybe buffer locking needs to be added.

**Comment by barrett-ruth** [comment]
@xiaoshihou514 can you be clear about how this happens? Is it that as a formatter runs and you try to save changes they're lost?

**Comment by xiaoshihou514** [comment]
@barrett-ruth fyi

**Comment by barrett-ruth** [comment]
I think we ought to implement buffer locking. I think this would happen just enough to be relevant and we ought to just fix it now.

**Comment by xiaoshihou514** [comment]
> However, this seems like a core problem of asychronous formatting in general... if we're locking a buffer during asynchronous formatting isn't that quite similar to the whole process being synchronous?

Well you could still move around, open splits, etc.

> Furthermore, how does vim.lsp.buf.format with { async = false } handle this? These are things to consider.

It just blocks and freezes the editor, much like `read !prettier "%"` or something similar.

**Comment by glepnir** [comment]
a clean reproduce step here  ?

**Comment by glepnir** [comment]
edit after the format, because async the buffer  content changed so the buffer lose new lines right ? there need  check `changedtick`
