### ISSUE TITLE
Multiple Filetypes in Config

### ISSUE THREAD

**Issue by barrett-ruth** [nvimdev/guard.nvim#37]
Why are multiple filetypes provided as a single string with comma delimiters instead of a table? I think that would be a more useful interface.

**Comment by xiaoshihou514** [comment]
The impl is much cleaner while the functionality is pretty much the same.

**Comment by barrett-ruth** [comment]
The implementation varies by a singular if statement and for loop, not to mention it just makes more sense.
Whatever, it's not actually an issue I guess.
