### ISSUE TITLE
Feature Request: Condition Formatting

### ISSUE THREAD

**Issue by barrett-ruth** [nvimdev/guard.nvim#40]
I opened up an issue for extra arguments which you quickly implemented - thanks! This is the other problem I think should be best opened up here separately:

In null-ls one can avoid formatting if a certain "condition" is not met like so:

        diagnostics.eslint_d.with({
            condition = function(utils)
                return utils.root_has_file({
                    {
                        '.eslintrc',
                        '.eslintrc.cjs',
                        '.eslintrc.yaml',
                        '.eslintrc.yml',
                        '.eslintrc.json',
                    },
                })
            end,
        }),

**Comment by glepnir** [comment]
I had write usage in that pr i think `tool.find`  like 

```lua
ft('c'):({ cmd = 'clang-format' ,find = '.clang-format'})
```
