### ISSUE TITLE
feat: support environment specification

### ISSUE THREAD

**Issue by barrett-ruth** [nvimdev/guard.nvim#44]
Support environment variable spec like how [null-ls does](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#environment-variables)

Should simply pass a dict to env in "uv.spawn" call in format.

Maybe implemented like so?

```lua
ft('ft')
    :fmt('fmt')
    :env({ ENVVAR = 'VAL' })
```

**Comment by glepnir** [comment]
yup . maybe is that
