### ISSUE TITLE
[Discussion] Strip formatting and lint tools to a collection repo ?

### ISSUE THREAD

**Issue by glepnir** [nvimdev/guard.nvim#61]
More and more formatting and lint tools are added to guard. The number of these tools will increase exponentially. But the tools you use may only have very few. Then the rest of these tool configurations still exist locally. It doesn't seem to matter. Because maybe one day in the future you can easily enable it when you need it. But for some tools you may never use them. Even get bored with collections of these configurations. So I want to strip them into a guard-collection repo. Consider the following points

1. If you don't care about these. Just want to simply configure the tool you can use guard and guard-collection
2. if you want to keep everything as simple as possible. Then you can copy the tool configuration you need to your own configuration and register it through the filetype module.

any thought?

**Comment by xiaoshihou514** [comment]
+1 on this, currently this repo has 700 something lines of functionality code, null-ls has nearly 10k LOC for builtin tools.

**Comment by barrett-ruth** [comment]
+1. null-ls is always a great example to point to for what goes right and what goes wrong, @xiaoshihou514 is absolutely correct.

Reference guard-collection in the readme and extract all tools there sounds like a good idea.

**Comment by jinzhongjia** [comment]
yes, readme maybe a good idea, If you think it is difficult to manage, you can directly open discussions

Obtaining can refer to a method similar to mason, which provides an additional registration library, and then downloads the configuration file

**Comment by barrett-ruth** [comment]
@xiaoshihou514 when will we finalize this change into main repo

**Comment by xiaoshihou514** [comment]
@barrett-ruth depends on when would @glepnir approve #94 . It's been working for me locally, you can try out my fork to test out for bugs.

**Comment by xiaoshihou514** [comment]
#100

**Comment by barrett-ruth** [comment]
@xiaoshihou514 please use "!" w/ commits that have breaking changes
