### ISSUE TITLE
Formatter and linter not working before update

### ISSUE THREAD

**Issue by yebt** [nvimdev/guard.nvim#77]
This si the config
```lua
	local ft = require("guard.filetype")
	local lint = require("guard.lint")

	ft("python"):fmt({
		cmd = "black",
		args = {
			"--quiet",
			"--stdin-filename",
		},
		stdin = true
	}):lint("pylint")


	require("guard").setup({
		-- -- the only options for the setup function
		 fmt_on_save = true,
		-- -- Use lsp if no formatter was defined for this filetype
		lsp_as_default_formatter = false,
	})
```

But the linter not

**Comment by barrett-ruth** [comment]
BTW black config doesn't require --stdin-filename arg, and if it did, you'd have to pass `fname = true` as the last arg to the setup.

Use this instead:
ft("python"):fmt({
		cmd = "black",
		args = {
			"-",
		},
		stdin = true
	}):lint("pylint")

**Comment by yebt** [comment]
still not working

**Comment by yebt** [comment]
still not working

**Comment by xiaoshihou514** [comment]
Hi! @yebt could you check the following
- `checkhealth guard` to ensure the required binaries are present
- `au Guard` and see if there is an autocmd for the current bufnr(obtainable from `echo bufnr("%")`
If both of these look fine could you repro with a minimal config(`nvim -u min.lua` and use `vim.o.rtp:append` to only load guard)
