### ISSUE TITLE
Feature requests: format without saving and default to LSP

### ISSUE THREAD

**Issue by heygarrett** [nvimdev/guard.nvim#8]
Hi! I couldn't find a way to run `:GuardFmt` or `require("guard.format").do_fmt()` without also saving the changes to the file, so I figured I'd request it as a feature.

Secondly, is there, or could there be, a way to fall back to LSP formatting if guard is not configured for the current filetype? Maybe something like `ft("default"):fmt("lsp")` or an additional option in the setup call? Another possibility would be for `do_fmt()` to return some sort of success or failure so I could use that to determine whether I should run my own formatting logic with installed language servers.

Just some thoughts! Thanks.

**Comment by glepnir** [comment]
>  I couldn't find a way to run :GuardFmt or require("guard.format").do_fmt() without also saving the changes to the file, so I figured I'd request it as a feature.

Sorry I don't understand this. if you set `fmt_on_save` to false, you can also use `GuardFmt` to format file or visual select area.

**Comment by erikzaadi** [comment]
Added the default lsp support in https://github.com/nvimdev/guard.nvim/pull/16

**Comment by heygarrett** [comment]
@glepnir I do want to format on save, but I *don't* want to save on format.

**Comment by xiaoshihou514** [comment]
You can make a pr that removes [https://github.com/nvimdev/guard.nvim/blob/main/lua/guard/format.lua#L56-L56](this line).

**Comment by xsh005** [comment]
You can make a pr that removes [this line](https://github.com/nvimdev/guard.nvim/blob/main/lua/guard/format.lua#L56-L56).

**Comment by heygarrett** [comment]
@xsh005 I could, but I don't want to break someone else's workflow. I suppose I could try adding a `save_on_format` option. 🤔

**Comment by glepnir** [comment]
because it's async so there added `write` command .

**Comment by heygarrett** [comment]
@glepnir Yeah, that would be great!
