### ISSUE TITLE
Can't add arguments to clang-format

### ISSUE THREAD

**Issue by jckli** [nvimdev/guard.nvim#83]
Would like to say first of all, great plugin by the way.

However I was wondering, how can I add arguments to clang-format? I keep trying to add the --style argument however now whenever I save and guard tries to format, I get an error and it doesn't format anything. Without any arguments, the clang-format works and formats, however I would like to change some factors of the command, hence my arguments.

The arguments do work and actually formats when I use them in the actual command.

Here's my guard config file
```lua
local ft = require("guard.filetype")

ft("c,cpp"):fmt({
	cmd = "clang-format",
	args = { "--style='{BasedOnStyle: Google, UseTab: Always, IndentWidth: 8, TabWidth: 8}'" },
	stdin = true,
})
ft("typescript,javascript,typescriptreact,javascriptreact"):fmt("prettierd")

require("guard").setup({
    -- the only options for the setup function
    fmt_on_save = true,
    -- Use lsp if no formatter was defined for this filetype
    lsp_as_default_formatter = false,
})
```

Thanks!

**Comment by xiaoshihou514** [comment]
Does it work without the single quotes?
```lua
args = { "--style={BasedOnStyle: Google, UseTab: Always, IndentWidth: 8, TabWidth: 8}" },
```

**Comment by jckli** [comment]
> Does it work without the single quotes?
> 
> ```lua
> args = { "--style={BasedOnStyle: Google, UseTab: Always, IndentWidth: 8, TabWidth: 8}" },
> ```

That was it! Thank you so much haha.
