### ISSUE TITLE
errors out on args in Go

### ISSUE THREAD

**Issue by effinsky** [nvimdev/guard.nvim#90]
I get a 
<img width="564" alt="Screenshot 2023-09-01 at 09 59 54" src="https://github.com/nvimdev/guard.nvim/assets/54535543/46cb9797-8721-443c-88b9-e626a1035482">

on 
```
ft("go"):fmt("lsp"):append {
	cmd = "goimports-reviser",
	args = { "-company-prefixes github.com/mycompany/" },
}

```
How to properly format the args? Thanks in advance.

**Comment by xiaoshihou514** [comment]
This is equivalent to running the following in a shell
```shell
goimports-revisor "-company-prefixes github.com/mycompany/"
```
with the latter being recognized as a single arg
This
```lua
args = { "-company-prefixes", "github.com/mycompany/" }
```
is equivalent to
```shell
goimports-revisor "-company-prefixes" "github.com/mycompany"
# same as
goimports-revisor -company-prefixes github.com/mycompany
```
which is probably what you want

**Comment by effinsky** [comment]
ok, thanks -- still errors out but I think that's because I'm not telling it to format the "current buffer" -- not giving it any path and it expects something there. Any idea what to do about that?

**Comment by glepnir** [comment]
`filename = true`

**Comment by effinsky** [comment]
ok thanks. still errors out. 

here's the line I need (confirmed to work from cmdline): 
`goimports-reviser -company-prefixes github.com/mycompany main.go`

my current relevant setup in `guard` config is: 
```
local ok, ft = pcall(require, "guard.filetype")
if not ok then return end

ft("go"):fmt("lsp"):append {
	cmd = "goimports-reviser",
	args = { "-company-prefixes", "github.com/mycompany/" },
	stdin = true,
	filename = true,
}

require("guard").setup {
	fmt_on_save = true,
}
```

**Comment by effinsky** [comment]
thanks!

**Comment by xiaoshihou514** [comment]
Glad to help!
