### ISSUE TITLE
Feature request: lazy load

### ISSUE THREAD

**Issue by Mephistophiles** [nvimdev/guard.nvim#91]
Hi here!
Thank you for the great plugin, but I would like it to load faster. Currently, according to the Lazy results, this plugin takes 19msec to load. It would be nice to have the ability for it to load before writing the file, thus speeding up the editor startup.

```
      ➜   guard.nvim 19.01ms
        ★   guard.nvim/plugin/guard.lua 16.01ms

```

**Comment by glepnir** [comment]
`event = BufEnter `
