### ISSUE TITLE
how to add codespell for all langauges as lint

### ISSUE THREAD

**Issue by nbari** [nvimdev/guard.nvim#96]
Hi, many thanks for all your time creating and sharing this plugin, This is my current  configuration, I am trying to add `codespell` as a linter for all the files:

```lua
local M = {
    "nvimdev/guard.nvim",
    event = "BufEnter"
}

M.keys = {
    {
        "<leader>ff",
        "<cmd>GuardFmt<cr>"
    }
}

M.config = function()
    local ft = require('guard.filetype')

    ft('json'):fmt({
        cmd = 'jq',
        stdin = true,
        args = {
            "--indent",
            "2"
        }
    })

    ft('*'):lint({
        cmd = 'codespell',
        stdin = true
})

    require('guard').setup({
        -- the only options for the setup function
        fmt_on_save = true,
        -- Use lsp if no formatter was defined for this filetype
        lsp_as_default_formatter = true
    })

end

return M
```

I don't get any errors but also do not get any warning about typos, how can I see logs or check if `codspell` is being called?

**Comment by glepnir** [comment]
currently ft only support filetype register. `*` is not support . should be support `*`.

**Comment by nbari** [comment]
This is what I am trying to use for ft `yaml`

```lua
    ft('yaml'):lint({
        cmd = 'codespell',
        stdin = true
})
```

But still, I don't see any warning, this is the file I am using for testing:

```yaml
---
- name: test thiss is a typro
  ansible.builtin.stat:
  path: {{ swap_file }}
```

I am expecting to have like a warning trying to replace `thiss` with `this`, any ideas of what could I be doing wrong?

**Comment by glepnir** [comment]
lint need a parser function convert stdout to neovim diagnostic.

**Comment by xiaoshihou514** [comment]
> currently ft only support filetype register. `*` is not support . should be support `*`.

Isn't * a valid pattern for a Filetype autocmd🤔?

**Comment by glepnir** [comment]
oh yep. I forget that. so problem is missing parser function ..

**Comment by nbari** [comment]
I am trying with file located in `tools/linter/codespell`:
```lua
local lint = require('guard.lint')
return {
    cmd = 'codespell',
    args = {
        '-'
    },
    stdin = true,
    parse = lint.from_regex({
        regex = '(%d+):%s*#.*\n%s*(.*?)%s*==>%s*(.*)',
       --- need more work here
        severities = {
         Warning = lint.severities.warning,
        },
        source = 'codespell'
 ```

The regex captures in 3 groups the output from `codespell`:

```
2: # noone
        noone ==> no one
19: # Regsitry
        Regsitry ==> Registry
```

Group 1 matches `2`,
Group 2 matches `noone`
Group 3 matches `no one`

How could I do some debugging to check that the file is called, (any place where the logs are written) also how to call the linter? 

If I run `GuardFmt` I get the error `missing config for filetype yaml` which is expected because I only have the `lint`.

Any ideas?

**Comment by glepnir** [comment]
this error should be fixed. I had try codespell this yaml file nothing print to stdout.

**Comment by xiaoshihou514** [comment]
The from_regex method defaults to one lint msg per line so if codespell has this format where messages break lines then you would need to write the parser function from scratch or attempt to use from_json.
This function parse gets the output of codespell and need to return a table as specified below:
```lua
{ 
     bufnr = buf, 
     col = col, 
     end_col = col, 
     end_lnum = lnum, 
     lnum = lnum, 
     message = message, 
     namespace = ns, 
     severity = severity, 
     source = source, 
 }
```
[This function](https://github.com/nvimdev/guard.nvim/blob/main/lua/guard/lint.lua#L72-L72) should help.
Linter diagnostic is supposed to refresh when triggered by a few events.

**Comment by xiaoshihou514** [comment]
codespell is now builtin, closing this issue
