### ISSUE TITLE
Plans to support code actions

### ISSUE THREAD

**Issue by sirreal** [nvimdev/guard.nvim#99]
Some linters have associated code actions such as fixes which can be applied or addition of lint disable comments. I don't think guard has any support for that yet. Are there plans to support code actions from linters?

**Comment by barrett-ruth** [comment]
@glepnir up to you.

looking at null-ls there is only three things they offer even after all this time: formatting, linting, and code actions.

While it's your decision if the project is out of scope I think guard.nvim is less appealing if we provide tools while not leveraging their full capabilities (i.e. code actions).

**Comment by xiaoshihou514** [comment]
@sirreal Maybe could you list some linters with this kind of feature?

**Comment by kassio** [comment]
Not a linter, but I use the gitsigns and refactoring.nvim  code actions all the time. Not sure how/if they fit here though. 😅

**Comment by barrett-ruth** [comment]
@xiaoshihou514 https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/code_actions

**Comment by sirreal** [comment]
Eslint (or eslint_d) is one I'm familiar with that will suggest fixes.

Apart from applying linter-provided fixes, it's very handy to have a code action to quickly add disable comments for lint rules on a line with a lint violation. That's something that can be supported apart from applying suggestions/fixes that the linter provides.

**Comment by xiaoshihou514** [comment]
> @xiaoshihou514 https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/code_actions

I already took a look in there and it seems there's only really eslint and a few spellcheck linters.

> Eslint (or eslint_d) is one I'm familiar with that will suggest fixes.

Don't do js but @glepnir recommended using it as an lsp

> Apart from applying linter-provided fixes, it's very handy to have a code action to quickly add disable comments for lint rules on a line with a lint violation. That's something that can be supported apart from applying suggestions/fixes that the linter provides.

That sounds handy, but I am not certain that linters have a convention for that. If not some extra logic have to be done to parse that ourselves to filter diagnostics (a function that runs after lint to remove disabled lint results)

**Comment by barrett-ruth** [comment]
Actually I recently switched to eslint as an LSP. Just as fast, no daemon issues. Would recommend @sirreal

**Comment by MoritzBoehme** [comment]
I would also be very interested.
My use case for this is a linter called statix for Nix, which has suggestions for linted errors/warnings like so:
```json
...
          "suggestion": {
            "at": {
              "from": {
                "line": 5,
                "column": 3
              },
              "to": {
                "line": 5,
                "column": 13
              }
            },
            "fix": "inherit abc;"
          }
...
```

**Comment by xiaoshihou514** [comment]
Just do it in `parse`.
